/* eslint-disable @typescript-eslint/no-explicit-any */
import type { McapConfig } from "./types";
import { service_list, getEntityBasicPrice, usaList } from "@/pages/Company/USA/constants";

export const US_FULL_CONFIG: McapConfig = {
  id: "us-full",
  countryCode: "US",
  countryName: "United States",
  currency: "USD",
  title: "usa.title",
  confirmationDetails: {
    title: "usa.congratsTitle",
    message: "We have collected your details and your US incorporation is now being processed. This typically takes 3-7 business days depending on the state. Our team will contact you if any further information is required.",
    steps: [
      {
        title: "State Documentation Review",
        description: "Our team reviews your selected state and entity type for compliance.",
      },
      {
        title: "Secretary of State Filing",
        description: "Documents are submitted to the chosen Secretary of State.",
      },
      {
        title: "Article approval & EIN",
        description: "Waiting for approved Articles of Organization/Incorporation and EIN application.",
      },
      {
        title: "Company Kit Delivery",
        description: "Digital delivery of your US company documents and operating agreement.",
      },
    ],
  },
  steps: [
    {
      id: "applicant",
      title: "usa.steps.step1",
      description: "usa.steps.applicant.description",
      fields: [
        { type: "text", name: "applicantName", label: "newHk.steps.applicant.fields.applicantName.label", required: true, colSpan: 2 },
        { type: "email", name: "applicantEmail", label: "newHk.steps.applicant.fields.email.label", required: true, colSpan: 2 },
        { type: "text", name: "applicantPhone", label: "newHk.steps.applicant.fields.phone.label", colSpan: 2 },
        { type: "text", name: "companyName1", label: "usa.AppInfo.usCompName", required: true, colSpan: 2 },
        { type: "text", name: "companyName2", label: "newHk.steps.applicant.fields.name2.label", colSpan: 2 },
        { type: "text", name: "companyName3", label: "newHk.steps.applicant.fields.name3.label", colSpan: 2 },
        {
          type: "checkbox-group",
          name: "establishedRelationshipType",
          label: "newHk.steps.applicant.fields.roles.label",
          required: true,
          colSpan: 2,
          options: [
            { label: "newHk.steps.applicant.fields.roles.options.Director", value: "Director" },
            { label: "newHk.steps.applicant.fields.roles.options.Shareholder", value: "Shareholder" },
            { label: "newHk.steps.applicant.fields.roles.options.Authorized", value: "Authorized" },
            { label: "newHk.steps.applicant.fields.roles.options.Professional", value: "Professional" },
            { label: "newHk.steps.applicant.fields.roles.options.Other", value: "Other" },
          ],
        },
        {
          type: "text",
          name: "otherRelationshipType",
          label: "Enter Other Value",
          condition: (f) => f.establishedRelationshipType?.includes("Other"),
        },
        {
          type: "select",
          name: "sns",
          label: "newHk.steps.applicant.fields.sns.label",
          options: [
            { label: "newHk.steps.applicant.fields.sns.options.WhatsApp", value: "WhatsApp" },
            { label: "newHk.steps.applicant.fields.sns.options.WeChat", value: "WeChat" },
            { label: "newHk.steps.applicant.fields.sns.options.Line", value: "Line" },
            { label: "newHk.steps.applicant.fields.sns.options.KakaoTalk", value: "KakaoTalk" },
            { label: "newHk.steps.applicant.fields.sns.options.Telegram", value: "Telegram" },
          ],
        },
        {
          type: "text",
          name: "snsId",
          label: "newHk.steps.applicant.fields.snsId.label",
          condition: (f) => !!f.sns,
        },
      ],
    },
    {
      id: "compliance",
      title: "usa.steps.step2",
      description: "newHk.steps.compliance.description",
      fields: [
        {
          type: "radio-group",
          name: "annualRenewalConsent",
          label: "usa.AppInfo.amlUsEstablishment",
          required: true,
          colSpan: 2,
          options: [
            { label: "newHk.steps.compliance.options.yes", value: "yes" },
            { label: "newHk.steps.compliance.options.no", value: "no" },
            { label: "usa.AppInfo.handleOwnIncorpo", value: "self_handle" },
            { label: "usa.AppInfo.didntIntedEveryYear", value: "no_if_fixed_cost" },
            { label: "usa.AppInfo.consultationRequired", value: "consultation_required" },
          ],
        },
        {
          type: "radio-group",
          name: "legalAndEthicalConcern",
          label: "newHk.steps.compliance.questions.legalAndEthicalConcern",
          required: true,
          colSpan: 2,
          options: [
            { label: "newHk.steps.compliance.options.yes", value: "yes" },
            { label: "newHk.steps.compliance.options.no", value: "no" },
            { label: "newHk.steps.compliance.options.unsure", value: "unsure" },
          ],
        },
        {
          type: "radio-group",
          name: "q_country",
          label: "newHk.steps.compliance.questions.q_country",
          required: true,
          colSpan: 2,
          options: [
            { label: "newHk.steps.compliance.options.yes", value: "yes" },
            { label: "newHk.steps.compliance.options.no", value: "no" },
            { label: "newHk.steps.compliance.options.unsure", value: "unsure" },
          ],
        },
        {
          type: "radio-group",
          name: "sanctionsExposureDeclaration",
          label: "newHk.steps.compliance.questions.sanctionsExposureDeclaration",
          required: true,
          colSpan: 2,
          options: [
            { label: "newHk.steps.compliance.options.yes", value: "yes" },
            { label: "newHk.steps.compliance.options.no", value: "no" },
            { label: "newHk.steps.compliance.options.unsure", value: "unsure" },
          ],
        },
        {
          type: "radio-group",
          name: "crimeaSevastapolPresence",
          label: "newHk.steps.compliance.questions.crimeaSevastapolPresence",
          required: true,
          colSpan: 2,
          options: [
            { label: "newHk.steps.compliance.options.yes", value: "yes" },
            { label: "newHk.steps.compliance.options.no", value: "no" },
            { label: "newHk.steps.compliance.options.unsure", value: "unsure" },
          ],
        },
        {
          type: "radio-group",
          name: "russianEnergyPresence",
          label: "newHk.steps.compliance.questions.russianEnergyPresence",
          required: true,
          colSpan: 2,
          options: [
            { label: "newHk.steps.compliance.options.yes", value: "yes" },
            { label: "newHk.steps.compliance.options.no", value: "no" },
            { label: "newHk.steps.compliance.options.unsure", value: "unsure" },
          ],
        },
      ],
    },
    {
      id: "company",
      title: "usa.steps.step3",
      fields: [
        {
          type: "select",
          name: "selectedEntity",
          label: "usa.usCompanyEntity",
          required: true,
          options: [
            { label: "LLC (limited liability company)", value: "LLC" },
            { label: "Corporation", value: "Corporation" },
            { label: "Consultation required before proceeding", value: "Consultation required" },
          ],
          colSpan: 2,
        },
        {
          type: "search-select",
          name: "selectedState",
          label: "usa.Section2StateQuestion",
          required: true,
          items: usaList,
          colSpan: 2,
        },
        {
          type: "text",
          name: "beneficialOwner",
          label: "usa.bInfo.shrldSection.benificialOwner",
          placeholder: "usa.bInfo.shrldSection.selectBenificial",
          required: true,
          colSpan: 2,
        },
        {
          type: "checkbox-group",
          name: "selectedIndustry",
          label: "usa.bInfo.selectIndustryItems",
          required: true,
          colSpan: 2,
          options: [
            { label: "usa.bInfo.iList.1", value: "cryptocurrency-related" },
            { label: "usa.bInfo.iList.2", value: "development-of-it-blockchain" },
            { label: "usa.bInfo.iList.3", value: "cryptocurrency-based-investment" },
            { label: "usa.bInfo.iList.4", value: "cryptocurrency-based-games" },
            { label: "usa.bInfo.iList.5", value: "foreign-exchange-trading" },
            { label: "usa.bInfo.iList.6", value: "finance-investment-advisory-loan" },
            { label: "usa.bInfo.iList.7", value: "trade-industry" },
            { label: "usa.bInfo.iList.8", value: "wholesaleretail-distribution-industry" },
            { label: "usa.bInfo.iList.9", value: "consulting" },
            { label: "usa.bInfo.iList.10", value: "manufacturing" },
            { label: "usa.bInfo.iList.11", value: "online-service-industry-e-commerce" },
            { label: "usa.bInfo.iList.12", value: "online-direct-purchasedeliverypurchase-agency" },
            { label: "usa.bInfo.pList.8", value: "other" },
          ],
        },
        {
          type: "text",
          name: "otherIndustryText",
          label: "usa.bInfo.pList.8",
          condition: (f) => Array.isArray(f.selectedIndustry) && f.selectedIndustry.includes("other"),
          colSpan: 2,
        },
        {
          type: "textarea",
          name: "descriptionOfProducts",
          label: "usa.bInfo.descProductName",
          required: true,
          colSpan: 2,
          rows: 3,
        },
        {
          type: "textarea",
          name: "descriptionOfBusiness",
          label: "usa.bInfo.descBusinessInfo",
          required: true,
          colSpan: 2,
          rows: 3,
        },
        {
          type: "text",
          name: "webAddress",
          label: "usa.bInfo.enterWeb",
          placeholder: "https://",
          colSpan: 2,
        },
        {
          type: "checkbox-group",
          name: "purposeOfEstablishmentCompany",
          label: "usa.bInfo.purposeEstablish",
          required: true,
          colSpan: 2,
          options: [
            { label: "usa.bInfo.pList.1", value: "business-diversification-through-regulatory" },
            { label: "usa.bInfo.pList.2", value: "advisor-or-client-suggested" },
            { label: "usa.bInfo.pList.3", value: "expanding-business-into-various-overseas-countries" },
            { label: "usa.bInfo.pList.4", value: "asset-management-by-investing-in-real-estate-or-financial" },
            { label: "usa.bInfo.pList.5", value: "holding-company" },
            { label: "usa.bInfo.pList.6", value: "pursuing-competitive-advantage-through-liberal" },
            { label: "usa.bInfo.pList.7", value: "increased-transaction-volume-due-to-low-tax-rate" },
            { label: "usa.bInfo.pList.8", value: "other" },
          ],
        },
        {
          type: "text",
          name: "otherCompanyPurposeText",
          label: "usa.bInfo.pList.8",
          condition: (f) => Array.isArray(f.purposeOfEstablishmentCompany) && f.purposeOfEstablishmentCompany.includes("other"),
          colSpan: 2,
        },
        {
          type: "select",
          name: "totalCapital",
          label: "usa.regDetails.totalPaid",
          tooltip: "usa.regDetails.totalPaidTtip",
          required: true,
          options: ["1", "100", "1000", "10000"].map(opt => ({ label: opt, value: opt })),
          colSpan: 1,
        },
        {
          type: "select",
          name: "companyExecutives",
          label: "usa.regDetails.executiveTeam",
          tooltip: "usa.regDetails.executiveTeamTtip",
          required: true,
          options: [
            "1 person",
            "2 or more individuals",
            "Corporation (agent participates in the decision-making of the U.S. company) + individual",
          ].map(opt => ({ label: opt, value: opt })),
          colSpan: 1,
        },
        {
          type: "select",
          name: "noOfSharesSelected",
          label: "usa.regDetails.totalNumShares",
          tooltip: "usa.regDetails.additionalCosts",
          required: true,
          options: [
            "Total capital divided by $1 (1 share price = $1; universal method)",
            "1 share (minimum) (1 share price = total capital)",
            "100",
            "1,000",
            "10,000",
          ].map(opt => ({ label: opt, value: opt })),
          colSpan: 2,
        },
      ],
    },
    {
      id: "services",
      title: "usa.steps.step5",
      description: "usa.steps.services.description",
      widget: "ServiceSelectionWidget",
      serviceItems: (data: any) => {
        const base = getEntityBasicPrice(data.selectedState || "", data.selectedEntity || "");
        const basePrice = Number(base?.price || 0);
        const baseLabel = `${data.selectedState || "State"} (${data.selectedEntity || "Entity"})`;

        const baseItem = {
          id: "base",
          label: baseLabel,
          amount: basePrice,
          original: basePrice,
          info: base?.note,
          mandatory: true,
        };

        const optionalItems = service_list.map((svc) => ({
          id: svc.id,
          label: svc.key,
          amount: Number(svc.price || 0),
          original: Number(svc.price || 0),
          mandatory: false,
        }));

        return [baseItem, ...optionalItems];
      },
    },
    {
      id: "invoice",
      title: "newHk.steps.invoice.title",
      description: "newHk.steps.invoice.description",
      widget: "InvoiceWidget",
    },
    {
      id: "parties",
      title: "newHk.steps.company.sections.c",
      description: "newHk.company.fields.inviteText",
      widget: "PartiesManager",
      minParties: 1,
      requireDcp: true,
      requirePartyInvite: true,
    },
    {
      id: "accounting",
      title: "newHk.steps.acct.title",
      fields: [
        {
          type: "textarea",
          name: "accountingDataAddress",
          label: "usa.bInfo.enterAddress",
          placeholder: "newHk.steps.acct.fields.softNote.placeholder",
          colSpan: 2,
          rows: 3,
        },
        {
          type: "select",
          name: "localCompanyRegistration",
          label: "usa.regDetails.usLocalReg",
          tooltip: "usa.regDetails.usLocalRegTtip",
          required: true,
          options: [
            "Use MirAsia’s U.S. company registration address service",
            "There is a separate address to use as a business address in the United States (do not use Mir Asia’s registered address service)",
          ].map(opt => ({ label: opt, value: opt })),
          colSpan: 2,
        },
        {
          type: "text",
          name: "businessAddress",
          label: "usa.regDetails.enterUsAddress",
          placeholder: "Street, City, State, ZIP",
          condition: (data) =>
            data.localCompanyRegistration ===
            "There is a separate address to use as a business address in the United States (do not use Mir Asia’s registered address service)",
          colSpan: 2,
        },
      ],
    },
    {
      id: "payment",
      title: "usa.steps.step7",
      description: "usa.steps.payment.description",
      widget: "PaymentWidget",
      supportedCurrencies: ["USD", "HKD"],
    },
    // {
    //   id: "registration-details",
    //   title: "usa.steps.step8",
    //   fields: [
    //     {
    //       type: "info",
    //       label: "newHk.review.declarations.title",
    //       colSpan: 2,
    //     },
    //     {
    //       type: "checkbox",
    //       name: "truthfulnessDeclaration",
    //       label: "newHk.review.declarations.truth",
    //       required: true,
    //       colSpan: 2,
    //     },
    //     {
    //       type: "checkbox",
    //       name: "legalTermsAcknowledgment",
    //       label: "newHk.review.declarations.terms",
    //       required: true,
    //       colSpan: 2,
    //     },
    //     {
    //       type: "checkbox",
    //       name: "compliancePreconditionAcknowledgment",
    //       label: "newHk.review.declarations.compliance",
    //       required: true,
    //       colSpan: 2,
    //     },
    //     {
    //       type: "text",
    //       name: "eSign",
    //       label: "newHk.review.esign.label",
    //       tooltip: "newHk.review.esign.helper",
    //       placeholder: "newHk.review.placeholders.signaturePlaceholder",
    //       required: true,
    //       colSpan: 2,
    //     },
    //   ],
    // },
  ],
};
