import { BillableItem, QuoteLanguage, QuoteLayout } from '../InvoiceManager/invoiceM';

export const LOCALE_BY_LANG: Record<QuoteLanguage, string> = {
    en: 'en-US',
    ko: 'ko-KR',
    zhTW: 'zh-TW',
};

export const DEFAULT_LAYOUT: QuoteLayout = {
    companyName: 'MIRR ASIA',
    companyDetails: [
        'MIRR ASIA BUSINESS ADVISORY & SECRETARIAL COMPANY LIMITED',
        'WORKSHOP UNIT B50 & B58, 2/F, 36-40 Tai Lin Pai Road',
        'KWAI CHUNG, N.T. Hong Kong',
        'Email: cs@mirrasia.com | Phone: +82-2-543-6187',
    ],
    badgeText: 'DRAFT QUOTE',
    notesTitle: 'Notes',
    notesLines: [
        'Additional charges for accounting and tax support may apply.',
        'This is a digital quote generated via Mirrasia App.',
    ],
    legalTermsTitle: 'Legal Terms',
    legalTermsLines: [
        'Payment method: overseas transfer or card payment (3.5% fee for card payments).',
        'KYC/Due Diligence is required before service commencement.',
        'Regulatory licensing requirements may apply based on business scope.',
    ],
    supportMessage: 'If you have any questions about this quotation, contact us via the channels below.',
    thankYouMessage: 'Thank you for considering MIRR ASIA.',
    signatureName: 'MIRR ASIA Team',
    generatedByText: 'Generated by MIRRASIA Proprietary Quotation Engine',
    emailFooter: 'This is a digital quotation generated via the Mirrasia App.',
    footerText: '2026 MIRR ASIA BUSINESS ADVISORY & SECRETARIAL COMPANY LIMITED. All rights reserved.',
    contacts: [
        { label: 'Email', value: 'cs@mirrasia.com', href: 'mailto:cs@mirrasia.com' },
        { label: 'Telephone (Korea)', value: '+82-2-543-6187' },
    ],
    labels: {
        quotation: 'Quotation',
        quoteNumber: 'Quote #',
        date: 'Date',
        expires: 'Expires',
        expiresValue: '30 Days from issue',
        recipient: 'Recipient',
        qty: 'Qty',
        productOrService: 'Product or Service',
        unitPrice: 'Unit Price',
        lineTotal: 'Line Total',
        amountUsd: 'Amount (USD)',
        totalPrice: 'Total Price',
        preparedFor: 'Prepared For',
        validFor: 'Valid for 30 days',
        draftQuote: 'Draft Quotation',
    },
};

export type LayoutForm = {
    companyName: string;
    companyDetails: string;
    badgeText: string;
    notesTitle: string;
    notesLines: string;
    legalTermsTitle: string;
    legalTermsLines: string;
    footerText: string;
    quotationLabel: string;
    recipientLabel: string;
    totalLabel: string;
};

export const cloneLayout = (layout: QuoteLayout) => JSON.parse(JSON.stringify(layout)) as QuoteLayout;

export const normalizeLanguage = (value?: string): QuoteLanguage => {
    const raw = String(value || '').trim().toLowerCase();
    if (raw === 'ko' || raw === 'ko-kr') return 'ko';
    if (raw === 'zh' || raw === 'zh-hk' || raw === 'zh-tw' || raw === 'zhtw') return 'zhTW';
    return 'en';
};

export const toLines = (value: string) => String(value || '').split(/\r?\n/).map((v) => v.trim()).filter(Boolean);
export const toText = (lines?: string[]) => (Array.isArray(lines) ? lines.join('\n') : '');

export const mergeLayout = (incoming?: Partial<QuoteLayout> | null): QuoteLayout => {
    const base = cloneLayout(DEFAULT_LAYOUT);
    if (!incoming) return base;
    return {
        ...base,
        ...incoming,
        companyDetails: Array.isArray(incoming.companyDetails) ? incoming.companyDetails : base.companyDetails,
        notesLines: Array.isArray(incoming.notesLines) ? incoming.notesLines : base.notesLines,
        legalTermsLines: Array.isArray(incoming.legalTermsLines) ? incoming.legalTermsLines : base.legalTermsLines,
        labels: { ...base.labels, ...(incoming.labels || {}) },
        contacts: Array.isArray(incoming.contacts) ? incoming.contacts : base.contacts,
    };
};

export const getItemText = (item: BillableItem, language: QuoteLanguage, fallbackTitle = 'Untitled Service') => {
    const localized =
        item.localizations?.[language] ||
        item.localizations?.en;
    return {
        title: String(localized?.title || item.title || '').trim() || fallbackTitle,
        description: String(localized?.description || item.description || '').trim(),
    };
};

export const layoutToForm = (layout: QuoteLayout): LayoutForm => ({
    companyName: layout.companyName || '',
    companyDetails: toText(layout.companyDetails),
    badgeText: layout.badgeText || '',
    notesTitle: layout.notesTitle || '',
    notesLines: toText(layout.notesLines),
    legalTermsTitle: layout.legalTermsTitle || '',
    legalTermsLines: toText(layout.legalTermsLines),
    footerText: layout.footerText || '',
    quotationLabel: layout.labels.quotation || '',
    recipientLabel: layout.labels.recipient || '',
    totalLabel: layout.labels.totalPrice || '',
});

export const formToLayout = (form: LayoutForm, base: QuoteLayout): QuoteLayout => ({
    ...base,
    companyName: form.companyName.trim(),
    companyDetails: toLines(form.companyDetails),
    badgeText: form.badgeText.trim(),
    notesTitle: form.notesTitle.trim(),
    notesLines: toLines(form.notesLines),
    legalTermsTitle: form.legalTermsTitle.trim(),
    legalTermsLines: toLines(form.legalTermsLines),
    footerText: form.footerText.trim(),
    labels: {
        ...base.labels,
        quotation: form.quotationLabel.trim(),
        recipient: form.recipientLabel.trim(),
        preparedFor: form.recipientLabel.trim(),
        totalPrice: form.totalLabel.trim(),
    },
});

export const formatDate = (language: QuoteLanguage, rawDate?: string) =>
    new Date(rawDate || Date.now()).toLocaleDateString(LOCALE_BY_LANG[language], {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
