name: ec2 testing Deployment
 
on:
  push:
    branches:
      - main
jobs:      
  DeployOnEc2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
 
    - name: Install dependencies
      run: npm install --legacy-peer-deps
 
    # login to aws first 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1   
    - name: Fetch .env file from S3
      run: |
        aws s3 cp s3://mirrasia-assets/mirrasia.env .env
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build
      run: CI="" npm run build

    # - name: Deploy static site to S3 bucket
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./dist/ s3://mirrasia --delete   
    
    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: E34MMIY5XJUV7N
        PATHS: "/*"
        AWS_REGION: "ap-southeast-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
